// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package internal

import (
	"fmt"
	"sync"

	typed "sigs.k8s.io/structured-merge-diff/v4/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.ironcore-dev.metal.api.v1alpha1.Aggregate
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.AggregateSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.AggregateStatus
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.AggregateItem
  map:
    fields:
    - name: aggregate
      type:
        scalar: string
    - name: sourcePath
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.JSONPath
    - name: targetPath
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.JSONPath
- name: com.github.ironcore-dev.metal.api.v1alpha1.AggregateSpec
  map:
    fields:
    - name: aggregates
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.AggregateItem
          elementRelationship: atomic
- name: com.github.ironcore-dev.metal.api.v1alpha1.AggregateStatus
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.metal.api.v1alpha1.AggregationResults
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.metal.api.v1alpha1.BlockSpec
  map:
    fields:
    - name: model
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: partitionTable
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PartitionTableSpec
    - name: rotational
      type:
        scalar: boolean
      default: false
    - name: size
      type:
        scalar: numeric
    - name: system
      type:
        scalar: string
    - name: type
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.CPUSpec
  map:
    fields:
    - name: addressSizes
      type:
        scalar: string
    - name: bogoMips
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: bugs
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: cacheAlignment
      type:
        scalar: numeric
    - name: cacheSize
      type:
        scalar: string
    - name: clFlushSize
      type:
        scalar: numeric
    - name: cores
      type:
        scalar: numeric
    - name: cpuIdLevel
      type:
        scalar: numeric
    - name: family
      type:
        scalar: string
    - name: flags
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: fpu
      type:
        scalar: boolean
      default: false
    - name: fpuException
      type:
        scalar: boolean
      default: false
    - name: logicalIds
      type:
        list:
          elementType:
            scalar: numeric
          elementRelationship: atomic
    - name: mhz
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: microcode
      type:
        scalar: string
    - name: model
      type:
        scalar: string
    - name: modelName
      type:
        scalar: string
    - name: physicalId
      type:
        scalar: numeric
    - name: powerManagement
      type:
        scalar: string
    - name: siblings
      type:
        scalar: numeric
    - name: stepping
      type:
        scalar: string
    - name: vendorId
      type:
        scalar: string
    - name: vmxFlags
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: wp
      type:
        scalar: boolean
      default: false
- name: com.github.ironcore-dev.metal.api.v1alpha1.ConsoleProtocol
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: port
      type:
        scalar: numeric
      default: 0
- name: com.github.ironcore-dev.metal.api.v1alpha1.ConstraintSpec
  map:
    fields:
    - name: agg
      type:
        scalar: string
    - name: eq
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.ConstraintValSpec
    - name: gt
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: gte
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: lt
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: lte
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: neq
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.ConstraintValSpec
    - name: path
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.JSONPath
- name: com.github.ironcore-dev.metal.api.v1alpha1.ConstraintValSpec
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.metal.api.v1alpha1.DistroSpec
  map:
    fields:
    - name: asicType
      type:
        scalar: string
    - name: buildBy
      type:
        scalar: string
    - name: buildDate
      type:
        scalar: string
    - name: buildNumber
      type:
        scalar: numeric
    - name: buildVersion
      type:
        scalar: string
    - name: commitID
      type:
        scalar: string
    - name: debianVersion
      type:
        scalar: string
    - name: kernelVersion
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.HostSpec
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
- name: com.github.ironcore-dev.metal.api.v1alpha1.IPMISpec
  map:
    fields:
    - name: ipAddress
      type:
        scalar: string
    - name: macAddress
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.Inventory
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.InventorySpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.InventoryStatus
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.InventorySpec
  map:
    fields:
    - name: blocks
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.BlockSpec
          elementRelationship: atomic
    - name: cpus
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.CPUSpec
          elementRelationship: atomic
    - name: distro
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.DistroSpec
    - name: host
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.HostSpec
    - name: ipmis
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.IPMISpec
          elementRelationship: atomic
    - name: memory
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.MemorySpec
    - name: nics
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.NICSpec
          elementRelationship: atomic
    - name: numa
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.NumaSpec
          elementRelationship: atomic
    - name: pciDevices
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceSpec
          elementRelationship: atomic
    - name: system
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.SystemSpec
    - name: virt
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.VirtSpec
- name: com.github.ironcore-dev.metal.api.v1alpha1.InventoryStatus
  map:
    fields:
    - name: computed
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.AggregationResults
    - name: inventoryStatuses
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.InventoryStatuses
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.InventoryStatuses
  map:
    fields:
    - name: ready
      type:
        scalar: boolean
      default: false
    - name: requestsCount
      type:
        scalar: numeric
- name: com.github.ironcore-dev.metal.api.v1alpha1.JSONPath
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.metal.api.v1alpha1.LLDPSpec
  map:
    fields:
    - name: capabilities
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: chassisId
      type:
        scalar: string
    - name: portDescription
      type:
        scalar: string
    - name: portId
      type:
        scalar: string
    - name: systemDescription
      type:
        scalar: string
    - name: systemName
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.Machine
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.MachineSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.MachineStatus
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.MachineClaim
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.MachineClaimSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.MachineClaimStatus
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.MachineClaimNetworkInterface
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: prefix
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.Prefix
- name: com.github.ironcore-dev.metal.api.v1alpha1.MachineClaimSpec
  map:
    fields:
    - name: ignitionSecretRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: image
      type:
        scalar: string
      default: ""
    - name: machineRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: machineSelector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
    - name: networkInterfaces
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.MachineClaimNetworkInterface
          elementRelationship: atomic
    - name: power
      type:
        scalar: string
      default: ""
- name: com.github.ironcore-dev.metal.api.v1alpha1.MachineClaimStatus
  map:
    fields:
    - name: phase
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.MachineNetworkInterface
  map:
    fields:
    - name: IPRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: macAddress
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
    - name: switchRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
- name: com.github.ironcore-dev.metal.api.v1alpha1.MachineSpec
  map:
    fields:
    - name: asn
      type:
        scalar: string
    - name: cleanupRequired
      type:
        scalar: boolean
    - name: inventoryRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: locatorLED
      type:
        scalar: string
    - name: loopbackAddressRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: machineClaimRef
      type:
        namedType: io.k8s.api.core.v1.ObjectReference
    - name: maintenance
      type:
        scalar: boolean
    - name: oobRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: power
      type:
        scalar: string
    - name: uuid
      type:
        scalar: string
      default: ""
- name: com.github.ironcore-dev.metal.api.v1alpha1.MachineStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: locatorLED
      type:
        scalar: string
    - name: manufacturer
      type:
        scalar: string
    - name: networkInterfaces
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.MachineNetworkInterface
          elementRelationship: atomic
    - name: power
      type:
        scalar: string
    - name: serialNumber
      type:
        scalar: string
    - name: shutdownDeadline
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: sku
      type:
        scalar: string
    - name: state
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.MemorySpec
  map:
    fields:
    - name: total
      type:
        scalar: numeric
- name: com.github.ironcore-dev.metal.api.v1alpha1.NDPSpec
  map:
    fields:
    - name: ipAddress
      type:
        scalar: string
    - name: macAddress
      type:
        scalar: string
    - name: state
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.NICSpec
  map:
    fields:
    - name: activeFEC
      type:
        scalar: string
    - name: lanes
      type:
        scalar: numeric
    - name: lldps
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.LLDPSpec
          elementRelationship: atomic
    - name: macAddress
      type:
        scalar: string
    - name: mtu
      type:
        scalar: numeric
    - name: name
      type:
        scalar: string
    - name: ndps
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.NDPSpec
          elementRelationship: atomic
    - name: pciAddress
      type:
        scalar: string
    - name: speed
      type:
        scalar: numeric
- name: com.github.ironcore-dev.metal.api.v1alpha1.NumaSpec
  map:
    fields:
    - name: cpus
      type:
        list:
          elementType:
            scalar: numeric
          elementRelationship: atomic
    - name: distances
      type:
        list:
          elementType:
            scalar: numeric
          elementRelationship: atomic
    - name: id
      type:
        scalar: numeric
      default: 0
    - name: memory
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.MemorySpec
- name: com.github.ironcore-dev.metal.api.v1alpha1.OOB
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.OOBSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.OOBStatus
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.OOBSecret
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.OOBSecretSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.OOBSecretStatus
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.OOBSecretSpec
  map:
    fields:
    - name: expirationTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: macAddress
      type:
        scalar: string
      default: ""
    - name: password
      type:
        scalar: string
      default: ""
    - name: username
      type:
        scalar: string
      default: ""
- name: com.github.ironcore-dev.metal.api.v1alpha1.OOBSecretStatus
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.metal.api.v1alpha1.OOBSpec
  map:
    fields:
    - name: consoleProtocol
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.ConsoleProtocol
    - name: endpointRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: flags
      type:
        map:
          elementType:
            scalar: string
    - name: macAddress
      type:
        scalar: string
      default: ""
    - name: protocol
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.Protocol
    - name: secretRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
- name: com.github.ironcore-dev.metal.api.v1alpha1.OOBStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: firmwareVersion
      type:
        scalar: string
    - name: manufacturer
      type:
        scalar: string
    - name: serialNumber
      type:
        scalar: string
    - name: state
      type:
        scalar: string
    - name: type
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
  map:
    fields:
    - name: id
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
- name: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceSpec
  map:
    fields:
    - name: address
      type:
        scalar: string
    - name: busId
      type:
        scalar: string
    - name: class
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
    - name: interface
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
    - name: subclass
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
    - name: subtype
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
    - name: subvendor
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
    - name: type
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
    - name: vendor
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.PCIDeviceDescriptionSpec
- name: com.github.ironcore-dev.metal.api.v1alpha1.PartitionSpec
  map:
    fields:
    - name: id
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: size
      type:
        scalar: numeric
- name: com.github.ironcore-dev.metal.api.v1alpha1.PartitionTableSpec
  map:
    fields:
    - name: partitions
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.PartitionSpec
          elementRelationship: atomic
    - name: type
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.Prefix
  scalar: untyped
- name: com.github.ironcore-dev.metal.api.v1alpha1.Protocol
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: port
      type:
        scalar: numeric
      default: 0
- name: com.github.ironcore-dev.metal.api.v1alpha1.Size
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.SizeSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.metal.api.v1alpha1.SizeStatus
      default: {}
- name: com.github.ironcore-dev.metal.api.v1alpha1.SizeSpec
  map:
    fields:
    - name: constraints
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.metal.api.v1alpha1.ConstraintSpec
          elementRelationship: atomic
- name: com.github.ironcore-dev.metal.api.v1alpha1.SizeStatus
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.metal.api.v1alpha1.SystemSpec
  map:
    fields:
    - name: id
      type:
        scalar: string
    - name: manufacturer
      type:
        scalar: string
    - name: productSku
      type:
        scalar: string
    - name: serialNumber
      type:
        scalar: string
- name: com.github.ironcore-dev.metal.api.v1alpha1.VirtSpec
  map:
    fields:
    - name: vmType
      type:
        scalar: string
- name: io.k8s.api.core.v1.LocalObjectReference
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: io.k8s.api.core.v1.ObjectReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldPath
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: resourceVersion
      type:
        scalar: string
    - name: uid
      type:
        scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.api.resource.Quantity
  scalar: untyped
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
      default: ""
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
      default: ""
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
  map:
    fields:
    - name: matchExpressions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
          elementRelationship: atomic
    - name: matchLabels
      type:
        map:
          elementType:
            scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
  map:
    fields:
    - name: key
      type:
        scalar: string
      default: ""
    - name: operator
      type:
        scalar: string
      default: ""
    - name: values
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        scalar: string
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
      default: ""
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
