// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// BootConfigurationSpecApplyConfiguration represents an declarative configuration of the BootConfigurationSpec type for use
// with apply.
type BootConfigurationSpecApplyConfiguration struct {
	MachineRef        *v1.LocalObjectReference `json:"machineRef,omitempty"`
	IgnitionSecretRef *v1.ObjectReference      `json:"ignitionSecretRef,omitempty"`
	Image             *string                  `json:"image,omitempty"`
}

// BootConfigurationSpecApplyConfiguration constructs an declarative configuration of the BootConfigurationSpec type for use with
// apply.
func BootConfigurationSpec() *BootConfigurationSpecApplyConfiguration {
	return &BootConfigurationSpecApplyConfiguration{}
}

// WithMachineRef sets the MachineRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineRef field is set to the value of the last call.
func (b *BootConfigurationSpecApplyConfiguration) WithMachineRef(value v1.LocalObjectReference) *BootConfigurationSpecApplyConfiguration {
	b.MachineRef = &value
	return b
}

// WithIgnitionSecretRef sets the IgnitionSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnitionSecretRef field is set to the value of the last call.
func (b *BootConfigurationSpecApplyConfiguration) WithIgnitionSecretRef(value v1.ObjectReference) *BootConfigurationSpecApplyConfiguration {
	b.IgnitionSecretRef = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *BootConfigurationSpecApplyConfiguration) WithImage(value string) *BootConfigurationSpecApplyConfiguration {
	b.Image = &value
	return b
}
