// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/ironcore-dev/metal/api/v1alpha1"
)

// BootConfigurationStatusApplyConfiguration represents an declarative configuration of the BootConfigurationStatus type for use
// with apply.
type BootConfigurationStatusApplyConfiguration struct {
	State *v1alpha1.BootConfigurationState `json:"state,omitempty"`
}

// BootConfigurationStatusApplyConfiguration constructs an declarative configuration of the BootConfigurationStatus type for use with
// apply.
func BootConfigurationStatus() *BootConfigurationStatusApplyConfiguration {
	return &BootConfigurationStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BootConfigurationStatusApplyConfiguration) WithState(value v1alpha1.BootConfigurationState) *BootConfigurationStatusApplyConfiguration {
	b.State = &value
	return b
}
