// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/metal/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/metal/client/applyconfiguration/api/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=metal.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Aggregate"):
		return &apiv1alpha1.AggregateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AggregateItem"):
		return &apiv1alpha1.AggregateItemApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AggregateSpec"):
		return &apiv1alpha1.AggregateSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BlockSpec"):
		return &apiv1alpha1.BlockSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleProtocol"):
		return &apiv1alpha1.ConsoleProtocolApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConstraintSpec"):
		return &apiv1alpha1.ConstraintSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CPUSpec"):
		return &apiv1alpha1.CPUSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DistroSpec"):
		return &apiv1alpha1.DistroSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostSpec"):
		return &apiv1alpha1.HostSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Inventory"):
		return &apiv1alpha1.InventoryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InventorySpec"):
		return &apiv1alpha1.InventorySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InventoryStatus"):
		return &apiv1alpha1.InventoryStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InventoryStatuses"):
		return &apiv1alpha1.InventoryStatusesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("IPMISpec"):
		return &apiv1alpha1.IPMISpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("LLDPSpec"):
		return &apiv1alpha1.LLDPSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Machine"):
		return &apiv1alpha1.MachineApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineClaim"):
		return &apiv1alpha1.MachineClaimApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineClaimNetworkInterface"):
		return &apiv1alpha1.MachineClaimNetworkInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineClaimSpec"):
		return &apiv1alpha1.MachineClaimSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineClaimStatus"):
		return &apiv1alpha1.MachineClaimStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineNetworkInterface"):
		return &apiv1alpha1.MachineNetworkInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineSpec"):
		return &apiv1alpha1.MachineSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineStatus"):
		return &apiv1alpha1.MachineStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MemorySpec"):
		return &apiv1alpha1.MemorySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NDPSpec"):
		return &apiv1alpha1.NDPSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NICSpec"):
		return &apiv1alpha1.NICSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NumaSpec"):
		return &apiv1alpha1.NumaSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OOB"):
		return &apiv1alpha1.OOBApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OOBSecret"):
		return &apiv1alpha1.OOBSecretApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OOBSecretSpec"):
		return &apiv1alpha1.OOBSecretSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OOBSpec"):
		return &apiv1alpha1.OOBSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OOBStatus"):
		return &apiv1alpha1.OOBStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PartitionSpec"):
		return &apiv1alpha1.PartitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PartitionTableSpec"):
		return &apiv1alpha1.PartitionTableSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PCIDeviceDescriptionSpec"):
		return &apiv1alpha1.PCIDeviceDescriptionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PCIDeviceSpec"):
		return &apiv1alpha1.PCIDeviceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Protocol"):
		return &apiv1alpha1.ProtocolApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Size"):
		return &apiv1alpha1.SizeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SizeSpec"):
		return &apiv1alpha1.SizeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SystemSpec"):
		return &apiv1alpha1.SystemSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VirtSpec"):
		return &apiv1alpha1.VirtSpecApplyConfiguration{}

	}
	return nil
}
