# permissions for end users to view inventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bootconfiguration-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: metal
    app.kubernetes.io/part-of: metal
    app.kubernetes.io/managed-by: kustomize
  name: bootconfiguration-viewer-role
rules:
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bootconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bootconfigurations/status
  verbs:
  - get
