---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.metal.ironcore.dev
  resources:
  - ips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.metal.ironcore.dev
  resources:
  - ips/status
  verbs:
  - get
- apiGroups:
  - metal.ironcore.dev
  resources:
  - inventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - inventories/status
  verbs:
  - get
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machineclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machineclaims/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machineclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - oobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - oobs/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - oobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - oobsecrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - oobsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - oobsecrets/status
  verbs:
  - get
  - patch
  - update
