name: Enable auto-merge

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    #if: ${{ (github.event.pull_request.draft == false) && (github.event.pull_request.user.login == 'dependabot[bot]') }}
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - name: Set up CLI
      uses: ksivamuthu/actions-setup-gh-cli@v3
    - name: Enable auto-merge
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
