name: Test E2E

on: pull_request

jobs:
  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: docker/setup-buildx-action@v3.3.0
    - uses: tale/kubectl-action@v1.4.0
      with:
        kubectl-version: v1.30.0
        # Empty kubeconfig file
        base64-kube-config: "YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQo="
    - name: Run tests
      run: make test-e2e
